core/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, email
from . import views

app_name = "core"

urlpatterns = [
    path('',views.index,name="index"),
    path('email/',views.email,name="email"),
]

magazine/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',views.index,name="index"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import uuid
from ckeditor.fields import RichTextField

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = RichTextField()
    def __str__(self):
        return self.title

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,max_length=30)
    writer = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    activation_key = models.SlugField(default="",editable=True,max_length=15,unique=True)

    def get_slug(self):
        uuid_value = str(uuid.uuid4())
        unique_slug = slugify(uuid_value[0:12])
        return unique_slug

    def __str__(self):
        return f'{self.user.username}'

    def save(self, *args, **kwargs):
        self.activation_key = self.get_slug()
        super().save(*args, **kwargs)

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import signals

@receiver(post_save,sender=User)
def save_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExist:
        pass
    else:
        instance.user.delete()
signals.post_delete.connect(delete_user, sender=Profile)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProfileForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(
        attrs = {
            'type' : 'email',
            'placeholder' : ('Email')
        }
    ))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
        }

    def clean(self):
        cleaned_data = super(ProfileForm,self).clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ProfileForm
from django.contrib.auth import authenticate, login
from .models import Post

# Create your views here.

def index(request):
    posts = Post.objects.all()
    latest = Post.objects.all()[0]
    context = {
        'posts' : posts,
        'latest' : latest
    }
    return render(request,'core/index.html', context)

def email(request):
    return render(request, 'core/email.html')

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Seamus Donnellan</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</head>
<body>
    <div class="container">

        <nav class="nav">
            <div class="nav__name">
                <h1 id="name-item">Seamus Donnellan</h1>
            </div>
            <div class="nav__items">
                <ul>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Work</a></li>
                    <li><a href="#">Hot Takes</a></li>
                    <div class="menu-icon">
                        <li class="menu" data-feather="menu"></li>
                    </div>
                </ul>
            </div>
        </nav>

        {% block content %} {% endblock %}

    </div>
    <script src="{% static 'js/app.js' %}"></script>
    <script>
        feather.replace()
    </script>
    <script>
        document.getElementById("name-item").addEventListener("click", () => {
            let url = "{% url 'core:email' %}";
            let state = {url: 'new-page.html', page: 2}
            //history.pushState(state, null, url);
            //location.href = "{% url 'core:email' %}";
        })
    </script>
</body>
</html>

core/templates/core/email.html
<h1>Welcome to the email page</h1>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div class="posts-container">
    <div class="flex-conn">
        <h1 id="h1_post">POSTS</h1>
        <small id="small_post"><a href="">View All</a></small>
    </div>
    <ul class="posts-slider">
        <li class="posts-slider__post">
            <div class="posts-slider__content">
                <h1>Post title here</h1>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui unde quo quae aspernatur adipisci odio maxime eius praesentium voluptatibus debitis consequatur, voluptates aliquam tempora est.</p>
                <button>Read More</button>
            </div>
        </li>
        <li class="posts-slider__post">
            <div class="posts-slider__content">
                <h1>Post title here</h1>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui unde quo quae aspernatur adipisci odio maxime eius praesentium voluptatibus debitis consequatur, voluptates aliquam tempora est.</p>
                <button>Read More</button>
            </div>
        </li>
        <li class="posts-slider__post">
            <div class="posts-slider__content">
                <h1>Post title here</h1>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui unde quo quae aspernatur adipisci odio maxime eius praesentium voluptatibus debitis consequatur, voluptates aliquam tempora est.</p>
                <button>Read More</button>
            </div>
        </li>
    </ul>
</div>

<div class="projects">
    <div class="projects__heading">
        <h1>What Am I Working On?</h1>
    </div>
    <div class="projects__featured">
        <h1><a href="#">Toko</a></h1>
        <p style="line-height: 30px;" class="grad-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni rerum atque aut cum pariatur fugit qui, labore minima cumque asperiores suscipit non vitae illo deleniti soluta, aliquam veniam inventore minus.</p>
        <button class="read-more">Read More</button>
    </div>
    <div class="projects__sub projects__first">
        <p class="grad-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda ratione laudantium nihil ex ipsa. Voluptatibus corporis odio adipisci unde molestias ea dolores non delectus expedita?</p>
    </div>
    <div class="projects__sub projects__second">
        <p class="grad-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil architecto vero quasi quisquam sapiente officiis delectus, doloribus illum ipsum repudiandae accusantium dignissimos ducimus impedit voluptatibus velit dolores aliquam eos? Hic.</p>
    </div>
</div>

<div class="hot-take">
    <div class="hot-take__text">
        <p class="hot-take__subhead">Weekly Political Segment</p>
        <h1 class="hot-take__heading">Hot Takes</h1>
        <p>
            A semi weekly segment where I talk talk about politics and other hot issues.
            It won’t be a consistent, some articles will be heavily opinionated, some won’t be.
            I am a boring conservative, so there most likely will be very few “extreme” opinions.
        </p>
    </div>
    <div class="hot-take__latest">
        <h1><a href="#">Post title here</a></h1>
        <p class="grad-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit et sunt cumque officiis veniam est quibusdam nobis placeat voluptatem dolore! Cupiditate reiciendis beatae minus, fugiat nemo voluptatum recusandae blanditiis numquam quae excepturi, doloribus cumque quia maiores quam accusamus aliquam provident!</p>
        <button class="read-more">Read More</button>
    </div>
</div>

{% endblock %}